"""icon table

Revision ID: a66f57f9eee6
Revises: 
Create Date: 2020-06-07 14:47:45.629549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a66f57f9eee6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icon',
    sa.Column('icon_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('base64', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('icon_id'),
    sa.UniqueConstraint('base64')
    )
    op.create_index(op.f('ix_icon_icon_id'), 'icon', ['icon_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_icon_icon_id'), table_name='icon')
    op.drop_table('icon')
    # ### end Alembic commands ###
